version: "3.7"

services:
  nginx:
    image: ${AWS_ECR_ACCOUNT_URL}/${DOCKER_IMAGE_NAME_NGINX}:latest
    ports:
      - "${DOCKER_HOST_PORT}:80"
    volumes:
      - type: bind
        source: .
        target: /var/www/html

  php-fpm:
    image: ${AWS_ECR_ACCOUNT_URL}/${DOCKER_IMAGE_NAME_PHP}:latest
    networks:
      - default
      - local-network
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./local.ini
        target: /usr/local/etc/php/conf.d/local.ini

networks:
  local-network:
    driver: bridge
    external: true
