version: "3.7"

services:
  cron:
    command: crond -f -l 2
    image: ${AWS_ECR_ACCOUNT_URL}/${DOCKER_IMAGE_NAME_PHP_FPM}:latest
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./local.ini
        target: /usr/local/etc/php/conf.d/local.ini
      - type: bind
        source: ./crontab
        target: /etc/crontabs/root

  nginx:
    image: ${AWS_ECR_ACCOUNT_URL}/${DOCKER_IMAGE_NAME_NGINX}:latest
    ports:
      - "${DOCKER_HOST_PORT}:80"
    volumes:
      - type: bind
        source: .
        target: /var/www/html

  php-fpm:
    image: ${AWS_ECR_ACCOUNT_URL}/${DOCKER_IMAGE_NAME_PHP_FPM}:latest
    networks:
      - default
      - local-network
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./local.ini
        target: /usr/local/etc/php/conf.d/local.ini

  queue:
    command: php artisan queue:listen --timeout=10800 --tries=1 --verbose
    image: ${AWS_ECR_ACCOUNT_URL}/${DOCKER_IMAGE_NAME_QUEUE}:latest
    volumes:
      - type: bind
        source: .
        target: /var/www/html
      - type: bind
        source: ./local.ini
        target: /usr/local/etc/php/conf.d/local.ini

networks:
  local-network:
    driver: bridge
    external: true
