version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11

jobs:
  register-ecs-task-definition:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "BEFORE:"
          command: echo ${CIRCLE_PROJECT_REPONAME}
      - run:
          name: "Setup custom environment variables"
          command: |
            echo 'export CIRCLE_PROJECT_REPONAME=$(echo "$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]')' >> $BASH_ENV
      - run:
          name: "AFTER:"
          command: echo ${CIRCLE_PROJECT_REPONAME}
      # - run:
      #     name: Register ECS task definition.
      #     command: |
      #       set -x
      #       sed -e "s;%REPO%;${CIRCLE_PROJECT_REPONAME};g" task-definition.json > task-definition-${CIRCLE_PROJECT_REPONAME}.json
      #       sed -e "s;%BRANCH%;${CIRCLE_BRANCH};g" task-definition-${CIRCLE_PROJECT_REPONAME}.json > task-definition-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.json
      #       sed -e "s;%IMAGE_TAG%;${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM};g" task-definition-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}.json > task-definition-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}.json

      #       aws ecs register-task-definition --region="${AWS_DEFAULT_REGION}" --family="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-task-definition" --cli-input-json file://task-definition-${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}.json

workflows:
  version: 2
  main-workflow:
    jobs:
      - aws-ecr/build-and-push-image:
          context: 'org-global'
          create-repo: true
          filters:
            branches:
              only:
                - dev
                - prod
          region: AWS_DEFAULT_REGION
          repo: $(echo "$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]')
          tag: '${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}'

      - register-ecs-task-definition
            context: 'aws'
            filters:
              branches:
                only:
                  - dev
                  - prod
            requires:
              - aws-ecr/build-and-push-image

      - aws-ecs/deploy-service-update:
          aws-region: ${AWS_DEFAULT_REGION}
          cluster-name: 'ecs-cluster'
          context: 'org-global'
          family: 'test'
          filters:
            branches:
              only:
                - dev
                - prod
          requires:
            - aws-ecr/build-and-push-image
            - register-ecs-task-definition
          service-name: test-service
