version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.11

jobs:
  register-ecs-task-definition:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: "Set an environment variable ($CIRCLE_PROJECT_REPONAME_LOWERCASE)"
          command: echo 'export CIRCLE_PROJECT_REPONAME_LOWERCASE=$(echo "$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]')' >> $BASH_ENV
      - run:
          name: "Make necessary replacements in task definition file"
          command: |
            set -x
            sed -i -e "s;%REPONAME%;${CIRCLE_PROJECT_REPONAME};g" task-definition.json
            sed -i -e "s;%REPONAME_LOWERCASE%;${CIRCLE_PROJECT_REPONAME_LOWERCASE};g" task-definition.json
            sed -i -e "s;%BRANCH%;${CIRCLE_BRANCH};g" task-definition.json
            sed -i -e "s;%AWS_ECR_ACCOUNT_URL%;${AWS_ECR_ACCOUNT_URL};g" task-definition.json
            sed -i -e "s;%IMAGE_TAG%;${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM};g" task-definition.json
      - run:
          name: "Register ECS task definition"
          command: aws ecs register-task-definition --family="${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-task-definition" --cli-input-json file://task-definition.json

workflows:
  version: 2
  main-workflow:
    jobs:
      - aws-ecr/build-and-push-image:
          context: 'org-global'
          create-repo: true
          filters:
            branches:
              only:
                - dev
                - prod
          region: AWS_DEFAULT_REGION
          repo: $(echo "$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]')
          tag: '${CIRCLE_BRANCH}-v${CIRCLE_BUILD_NUM}'

      - register-ecs-task-definition:
            context: 'org-global'
            filters:
              branches:
                only:
                  - dev
                  - prod
            requires:
              - aws-ecr/build-and-push-image

      - aws-ecs/deploy-service-update:
          aws-region: ${AWS_DEFAULT_REGION}
          cluster-name: 'ecs-cluster'
          context: 'org-global'
          family: '${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-task-definition'
          filters:
            branches:
              only:
                - dev
                - prod
          requires:
            - aws-ecr/build-and-push-image
            - register-ecs-task-definition
          service-name: '${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}-service'
